apiVersion: v1
kind: Service
metadata:
    name: "indiatestaks-2647"
    labels:
        app: "indiatestaks-2647"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
    selector:
        app: "indiatestaks-2647"